# Edificio nacional
db.host=192.168.1.80
db.service=igm1

# Apartamento del proceso actual
db.username=CNEDONBOSCO25
db.password=CNEDONBOSCO25

# Info del proceso
proceso.nombre=Elecciones Sevilla Don Bosco 2025
proceso.codigo=134
proceso.alcance=CANTONAL

proceso.id_kit=1